export const ColorSheet = {
    Primary: '#024D21',
    Secondary: '#DFDFDF',
    ActiveBottomTab: '#AFAC03',
    SecondaryBtnText: '#424B5A',
    Black: '#000000',
    White: '#FFFFFF',
    borderColor: '#EDEDED',
    Container: '#F0FFF6',
    Red: '#FF2828',
    GrayTxt: '#9F9F9F',
    Gray: '#F1F1F1',
    TopTabBorder: '#D9D9D9',
    ListBorder: '#EAEAEA',
    AddressTxt: '#A1A1A1',
    Pending: '#FB9F78',
    Expired: '#FF5454',
    AccordionCard: '#F3F3F3',
    LabelTxt: '#344054',
    PlaceHolder: '#ADADAD',
    Chit: '#F8F8F8',
    Delete: '#BC1A1A',
    FormLabel: '#9A9A9A',
  }
  